import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` h-full w-full bg-[#1D1D1D]`}>
        <Navbar />
        <main className="p-8">
          {children}
        </main>
        
      </body>
      
    </html>
  );
}
