import type { Metadata } from "next";
import "./globals.css";
import AppShell from "@/components/AppShell"; // Import the new client component
import { AuthProvider } from "@/components/AuthProvider";

// Now you can safely export metadata because this is a Server Component.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        {/* Use the AppShell to wrap the children. */}
        {/* The shell provides the interactive background/navbar, */}
        {/* while the {children} can still be Server Components. */}
         <AuthProvider>
        <AppShell>
         {children}
          </AppShell>
          </AuthProvider>
      </body>
    </html>
  );
}
